apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup-cronjob
  labels:
    {{- include "backups.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  schedule: {{ .Values.redisdb_cron_schedule | default "0 0 * * 1-5"}}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "backups.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "backups.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
{{- if .Values.redisimage.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.redisimage.imagePullSecrets }}
{{- end }}
          containers:
            - name: {{ .Chart.Name }}
              command:
                - /bin/sh
                - -c
                - |
                  backup_date=$(date +%d-%b-%Y-%s)
                  kubectl exec -it redis-master-0 -- redis-cli save
                  kubectl cp redis-master-0:/data/dump.rdb dump.rdb
                  tar cvf dump.rdb.tag.gz dump.rdb
                  mv dump.rdb.tag.gz dump-$backup_date.rdb.tag.gz
                  az storage blob upload --account-name {{ .Values.global.azure_storage_account_name }} \
                                          --account-key {{ .Values.global.azure_storage_account_key }} \
                                          --container-name {{ .Values.azure_backups_container_name }} \
                                          --name dump-$backup_date.rdb.tar.gz \
                                          --type block \
                                          --file "dump-$backup_date.rdb.tar.gz"
              image: "{{ .Values.redisimage.repository }}:{{ .Values.redisimage.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.redisimage.pullPolicy }}
